---
generic-service:
  nameOverride: hmpps-nomis-visits-mapping-service

  replicaCount: 4

  resources:
    requests:
      cpu: 100m
      memory: 640Mi
    limits:
      cpu: 2000m
      memory: 2048Mi

  image:
    repository: quay.io/hmpps/hmpps-nomis-visits-mapping-service
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: hmpps-nomis-visits-mapping-service-cert
    contextColour: green

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx1024m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  namespace_secrets:
    hmpps-nomis-visits-mapping-service:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
    dps-rds-instance-output:
      SPRING_FLYWAY_USER: "database_username"
      SPRING_FLYWAY_PASSWORD: "database_password"
      SPRING_R2DBC_USERNAME: "database_username"
      SPRING_R2DBC_PASSWORD: "database_password"
      DATABASE_NAME: "database_name"
      DATABASE_ENDPOINT: "rds_instance_endpoint"

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    petty-france-wifi: "213.121.161.112/28"
    global-protect: "35.176.93.186/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live-1: "35.178.209.113/32"
    cloudplatform-live-2: "3.8.51.207/32"
    cloudplatform-live-3: "35.177.252.54/32"

generic-prometheus-alerts:
  targetApplication: hmpps-nomis-visits-mapping-service
