---
# Per environment values which override defaults in hmpps-nomis-mapping-service/values.yaml

generic-service:
  ingress:
    host: nomis-sync-prisoner-mapping-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth

# CloudPlatform AlertManager receiver to route promethues alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: syscon-nonprod
  rdsAlertsDatabases:
    cloud-platform-51b5ee2cf4749f50: "Nomis mapping"
